"""Alembic environment for Atlas's own metadata store.

The connection string is read from `atlas.settings`, never from alembic.ini, so
there is one place a database URL is configured and no credential lands in a
file that gets committed.

There is no `target_metadata`. The schema is written by hand in the versions
below rather than autogenerated from ORM models — Atlas's domain models are
pydantic and describe what a claim *is*, not how a row stores it, and pointing
autogenerate at a second set of table definitions would make those definitions
the real schema.
"""

from __future__ import annotations

from alembic import context
from sqlalchemy import engine_from_config, pool

from atlas.settings import get_settings


def _url() -> str:
    """The database to migrate.

    A URL set on the config wins, so a caller holding a connection — a test
    against a throwaway container, an operator migrating one of several
    deployments — can say which one without exporting an environment variable
    that outlives the command.
    """
    configured = context.config.get_main_option("sqlalchemy.url", None)
    url = configured or get_settings().atlas_database_url
    if url is None:
        raise RuntimeError(
            "ATLAS_DATABASE_URL is not set; there is no database to migrate. "
            "Atlas defaults to the file-backed store, which has no schema."
        )
    return url


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = context.config.get_section(context.config.config_ini_section, {})
    section["sqlalchemy.url"] = _url()
    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(connection=connection)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
